export interface CafeTable {
  id: string;
  /** Raw table name entered by the user; numeric names are stored as strings. */
  number: string;
  /** Area or floor used to organize tables in the overview. */
  section?: string;
  status: 'free' | 'occupied' | 'billing';
  orderId?: string;
  orderStartTime?: number;
  pax?: number;
  /** Firebase conflict-resolution metadata. */
  syncRevision?: number;
  syncMutationId?: string;
  /** Opaque active-floor reset generation acknowledged by this occupancy. */
  activeFloorResetGeneration?: string;
}

export type CategoryPillar = string;
export type BeverageSubGroup = 'Non-Alcoholic' | 'Alcoholic';

export interface Category {
  id: string;
  name: string;
  order: number;
  /** When true, items in this category are included on KOT tickets to the kitchen printer */
  sendToKitchen?: boolean;
  /** One of the 4 super-category pillars */
  parentCategory?: CategoryPillar;
  /** Only for Beverages — groups the category under Non-Alcoholic or Alcoholic */
  subGroup?: BeverageSubGroup;
  /** Explicit printer route; takes precedence over sendToKitchen when present */
  printRoute?: PrintRoute;
}

export type PrintRoute = 'KOT' | 'BOT';

export interface MenuItemVariant {
  label: string;  // e.g. "60ml", "200g", "Large"
  price: number;
}

export interface MenuItem {
  id: string;
  categoryId: string;
  name: string;
  price: number;
  /** Printer routing: KOT → kitchen printer, BOT → bar/bottle printer */
  printRoute?: PrintRoute;
  image?: string;
  /** Optional descriptive fields used by menu search and imported menu data. */
  category?: string;
  categoryName?: string;
  subcategory?: string;
  subcategoryName?: string;
  description?: string;
  /** Whether the item is available for ordering. Defaults to true when absent. */
  available?: boolean;
  /** Multi-tier variants (e.g. peg sizes, portion sizes). When present, `price` holds the base/lowest tier. */
  variants?: MenuItemVariant[];
}

export interface OrderItem {
  id: string;
  menuItemId: string;
  name: string;
  price: number;
  quantity: number;
  /** Payment state – separate from kitchen state */
  status?: 'unpaid' | 'paid';
  paidAt?: number;
  /** Kitchen state: 'draft' = not yet sent, 'sent' = sent to kitchen */
  kitchenStatus?: 'draft' | 'sent';
  sentAt?: string | null;
  /** Legacy boolean flag kept for backward-compatibility */
  sentToKitchen?: boolean;
}

// ── KOT / BOT Ticket model ────────────────────────────────────────────────────

export type TicketType = 'KOT' | 'BOT' | 'VOID_KOT' | 'VOID_BOT';

export interface TicketItem {
  id: string;
  name: string;
  quantity: number;
  notes?: string;
}

/**
 * An incremental order ticket generated by sendToKitchen (KOT/BOT) or
 * voidOrderItem (VOID_KOT / VOID_BOT).  Stored on Order.tickets so every
 * device can see the full ticket history for a table session.
 */
export interface Ticket {
  id: string;
  orderId: string;
  tableId: string;
  tableName: string;
  ticketType: TicketType;
  /** Sequential counter per-order per-type: KOT #1, KOT #2, BOT #1, … */
  ticketNumber: number;
  items: TicketItem[];
  serverName: string;
  customerName?: string;
  createdAt: string;
  status: 'pending' | 'printed';
  /** For VOID tickets: reason for cancellation */
  voidReason?: string;
  /** For VOID tickets: who authorised the void */
  voidedBy?: string;
}

/** One cancelled/voided item line recorded on an order. */
export interface VoidRecord {
  id: string;
  itemId: string;
  name: string;
  quantity: number;
  price: number;
  reason: string;
  cancelledBy: string;
  cancelledAt: string;
}

export interface TablePayment {
  id: string;
  itemIds: string[];
  total: number;
  method: string;
  timestamp: number;
  billNumber: number;
}

export interface StaffAttribution {
  id: string;
  /** Normalised display name — always set via getStaffName() at write time */
  name: string;
  /** Forward-compat: some records may store the field as fullName */
  fullName?: string;
  role: string;
}

export interface Order {
  id: string;
  tableId: string;
  tableNumber: string;
  items: OrderItem[];
  status: 'active' | 'billed' | 'paid';
  kitchenStatus?: 'draft' | 'placed';
  hasUnsentItems?: boolean;
  createdAt: number;
  tablePayments?: TablePayment[];
  /** Staff member who created/took the order */
  takenBy?: StaffAttribution;
  /** Customer attached to this order for Khatta (credit ledger) tracking */
  attachedCustomer?: { id: string; name: string; phone: string; currentDue: number };
  /** Log of every voided / cancelled item on this order */
  voidHistory?: VoidRecord[];
  /** All KOT / BOT / VOID tickets generated for this order session */
  tickets?: Ticket[];
  /**
   * Per-station print confirmation for the auto-print hub.
   * Written as 'pending' when tickets are created (e.g. by a mobile waiter)
   * and flipped to 'printed' by the desktop hub after a successful USB dispatch.
   */
  printStatus?: {
    kot?: 'pending' | 'printed';
    bot?: 'pending' | 'printed';
  };
  /** Firebase conflict-resolution metadata. */
  syncRevision?: number;
  syncMutationId?: string;
  /** Opaque reset generations acknowledged by this order lifecycle. */
  activeFloorResetGeneration?: string;
  salesHistoryResetGeneration?: string;
}

export interface Payment {
  id: string;
  orderId: string;
  tableNumber: string;
  items: OrderItem[];
  subtotal: number;
  discount: number;
  discountType: 'percent' | 'fixed';
  vatAmount: number;
  vatRate: number;
  vatMode: 'excluded' | 'included';
  vatEnabled?: boolean;
  total: number;
  method: string;
  reference: string;
  createdAt: number;
  cafeName: string;
  billNumber: number;
  /** Opaque sales-history reset generation acknowledged by this payment. */
  salesHistoryResetGeneration?: string;
  /** Staff member who took the original order */
  takenBy?: StaffAttribution;
  /** Staff member who processed the payment */
  processedBy?: StaffAttribution;
  /** Customer associated with a Khatta payment, when applicable. */
  customerId?: string;
  /**
   * Previous Khatta due collected alongside this order, when the cashier
   * ticked "Include Previous Due". Kept out of `total` so revenue is not
   * double counted — the due was already booked as revenue when the Khatta
   * charge was recorded.
   */
  dueSettlement?: { customerId: string; amount: number; repaymentId: string };
  /** Cash/wallet actually collected: `total` plus any `dueSettlement.amount`. */
  amountTendered?: number;
}

export interface WalletConfig {
  enabled: boolean;
  qrImage?: string;
  logoImage?: string;
}

export interface CustomWallet {
  id: string;
  name: string;
  enabled: boolean;
  qrImage?: string;
  logoImage?: string;
}

export interface Ingredient {
  id: string;
  name: string;
  unit: string;
  quantity: number;
  threshold: number;
  category?: string;
  costPerUnit?: number;
}

export interface StockMovement {
  id: string;
  ingredientId: string;
  change: number;
  source: string;
  timestamp: number;
}

export interface RecipeIngredient {
  ingredientId: string;
  quantity: number;
}

export interface Recipe {
  menuItemId: string;
  ingredients: RecipeIngredient[];
}

// ── NEW INVENTORY TYPES ──────────────────────────────────────────────────────

export type InvProductType = 'alcohol' | 'beverage' | 'cigarette';
/** Operational inventory tabs. The productType above is retained for POS mappings. */
export type InventoryCategory = 'spirits' | 'wine' | 'beer' | 'soft-drinks' | 'cigarettes';
export type InvMovementType = 'Purchase' | 'Sale' | 'Adjustment' | 'Waste' | 'Correction';

export interface AlcoholProduct {
  id: string;
  name: string;
  category?: 'spirits' | 'wine';
  bottleSizeMl: number;       // e.g. 750
  currentStockMl: number;     // always stored in ml
  minStockMl: number;         // alert threshold in ml
  costPerBottle?: number;
  status: 'active' | 'inactive';
}

export interface BeverageProduct {
  id: string;
  name: string;
  category?: 'beer' | 'soft-drinks';
  packagingType: 'btl' | 'can' | 'pcs';
  sizeLabel?: string;         // e.g. 650ml, 330ml, 250ml
  currentStock: number;       // stored in pieces internally
  minStock: number;           // threshold in pieces internally
  costPerUnit?: number;
  /** Legacy fields accepted while older Firebase records are being edited. */
  piecesPerCarton?: number;
  costPerCarton?: number;
  status: 'active' | 'inactive';
}

export interface CigaretteProduct {
  id: string;
  name: string;
  sticksPerPacket: number;    // e.g. 20
  currentSticks: number;      // stored as total sticks internally
  minSticks: number;          // threshold in sticks internally
  costPerPacket?: number;
  status: 'active' | 'inactive';
}

export interface GroceryPurchase {
  id: string;
  item: string;
  qty: number;
  unit: string;               // kg, g, L, pcs, dozen, etc.
  cost: number;
  supplier?: string;
  invoiceNo?: string;
  date: string;               // ISO date string YYYY-MM-DD
  note?: string;
}

export interface InventoryMovement {
  id: string;
  productType: InvProductType;
  productId: string;
  productName: string;
  quantity: number;           // positive = stock in, negative = stock out (base unit)
  unit: string;               // ml / pcs / sticks
  type: InvMovementType;
  reference?: string;         // invoice # or order name
  reason?: string;
  supplier?: string;
  notes?: string;             // human-readable purchase details, e.g. "12 bottles × 750ml"
  timestamp: number;
  // ── Unified audit fields ──────────────────────────────────────────────────
  totalCost?: number;         // NPR cost for restock/purchase entries
  loggedBy?: string;          // staff member who logged this entry
  source?: 'bar' | 'inventory'; // origin: bar portal vs direct inventory form
  containerQty?: number;      // display qty in product units (bottles / cans / packets)
  containerUnit?: string;     // 'btl' | 'can' | 'pcs' | 'packet' | 'sticks'
}

export interface InvMenuMapping {
  id: string;
  menuItemId: string;
  productType: InvProductType;
  productId: string;
  deductQty: number;          // ml for alcohol, pieces for beverage, sticks for cigarette
}

// ── MAINTENANCE EXPENSES ─────────────────────────────────────────────────────

export type MaintenanceCategory =
  | 'plumbing'
  | 'electrical'
  | 'kitchen_equipment'
  | 'cottage_structure'
  | 'general';

export type MaintenancePaymentMethod = 'cash' | 'esewa' | 'khalti' | 'bank_transfer';

export interface MaintenanceExpense {
  id: string;
  title: string;
  category: MaintenanceCategory;
  amount: number;
  paymentMethod: MaintenancePaymentMethod;
  date: string;               // ISO date string yyyy-MM-dd
  loggedBy: string;
  createdAt: string;          // ISO datetime string
}

// ── CUSTOMER (Khatta / Credit Ledger) ────────────────────────────────────────

export interface Customer {
  id: string;
  name: string;
  phone: string;
  currentDue: number;   // Outstanding balance owed (NPR)
  totalSpend: number;   // Lifetime spend across all visits
  visits: number;       // Total number of visits
  /** Lifetime count of food items consumed across settled orders */
  foodItemsConsumed: number;
  /** Lifetime count of beverage items consumed across settled orders */
  beverageItemsConsumed: number;
  /** ISO datetime of the customer's most recent settled order */
  lastVisit?: string;
  /** Running per-item consumption tally used to rank favorite orders */
  topOrders?: Array<{ itemId: string; name: string; quantity: number; category: string }>;
  /** Durable marker proving this profile has acknowledged the latest credit reset. */
  creditResetRevision?: number;
  creditResetMutationId?: string;
}

/** A standalone payment received against a customer's outstanding Khatta balance. */
export interface CustomerRepayment {
  id: string;
  customerId: string;
  amount: number;
  method: 'cash' | 'fonepay';
  notes?: string;
  createdAt: number;
  receivedBy?: StaffAttribution;
}

// ── SETTINGS (unchanged) ─────────────────────────────────────────────────────

export interface Settings {
  cafeName: string;
  cafeLogo?: string;
  /** Aliases kept in sync with cafeLogo for cross-component compatibility */
  logo?: string;
  logoUrl?: string;
  cafeAddress?: string;
  cafePhone?: string;
  cafePan?: string;
  billFooter?: string;
  adminPin: string;
  esewaId: string;
  esewaPhone: string;
  wallets: {
    esewa: WalletConfig;
    khalti: WalletConfig;
    fonepay: WalletConfig;
  };
  customWallets?: CustomWallet[];
  printerAddress?: string;
  // ── Printer hardware configuration ──────────────────────────────────────────
  // Both stations are always driven via direct WebUSB ESC/POS. Device pairing
  // is device-local (localStorage: printer_kitchen_usb / printer_reception_usb).
  /** Enable kitchen printer buzzer/bell command on KOT print */
  kitchenPrinterBuzzer?: boolean;
  /** When true this device runs the background auto-print listener */
  autoPrintEnabled?: boolean;
  billCounter: number;
  kotCounter: number;
  resetKotDaily: boolean;
  kotLastResetDate?: string;
  vatEnabled: boolean;
  vatRate: number;
  vatMode: 'excluded' | 'included';
  showLogoOnBill: boolean;
  receiptFontSize: number;
  receiptFontFamily: string;
  stockEnforcementMode: 'flexible' | 'strict';
}
